version: "3.7"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./app/:/app
    tty: true

  db:
    image: mongo
    ports:
      - 27001:27001
    volumes:
      - "./dbdata:/data/db"
